# Use the official Go image as the base image
FROM golang:latest
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY ./backend ./backend
RUN go build ./backend/cmd/server
EXPOSE 8080
CMD ["./server"]